<?php
session_start();
error_reporting(E_ALL);
include_once("functions.php");
$messages=array();
$dbhost="localhost";
$dbuser="bestover_mysql";
$dbpass="8K8l6Q5x";
$dbname="bestover_auto";
connectToDB();
?>